language: csharp
solution: Botox.sln
install:
  - nuget restore Botox/Botox.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Botox/Botox.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Botox/BotoxTests/bin/Release/BotoxTests.dll
